/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.otakden.hello;

import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Properties;

public class App {
  public String getGreeting() throws IOException {
    return "Hello World";
  }
  
  public String getGreeting(Path propertiesFile) throws IOException {
    Properties properties = new Properties();
    try (InputStream inputStream = Files.newInputStream(propertiesFile)) {
      properties.load(inputStream);
    }
    return properties.getProperty("greeting");
  }

  public static void main(String[] args) throws IOException, URISyntaxException {
    System.out.println(new App().getGreeting());
  }
}
